export const esText = {
// Channel Titles
"Gen.1": "Creación",
"Gen.2": "Creación y resumen",
"Gen.3": "La caída del hombre",
"Gen.4": "Caín asesina a Abel",
"Gen.5": "Genealogías",
"Gen.6": "El diluvio",
"Gen.9": "El arcoíris y la pena capital",
"Gen.10": "Genealogías",
"Gen.11": "La torre de Babel",
"Gen.12": "El llamado de Abraham",
"Gen.13": "El conflicto de los vaqueros",
"Gen.14": "El secuestro de Lot",
"Gen.15": "Abraham creyó en Dios",
"Gen.16": "Nace Ismael",
"Gen.17": "Abram se convierte en Abraham",
"Gen.18": "Abraham ora por Sodoma",
"Gen.19": "Sodoma es destruido",
"Gen.20": "Abraham miente acerca de Sara en Gerar",
"Gen.21": "El nacimiento de Isaac",
"Gen.22": "La ofrenda de Isaac",
"Gen.23": "La muerte de Sara",
"Gen.24": "La novia para Isaac",
"Gen.25": "La muerte de Abraham",
"Gen.26": "El pacto abrahámico confirmado con Isaac",
"Gen.27": "El conflicto de primogenitura entre Jacob y Esaú",
"Gen.28": "El pacto abrahámico confirmado con Jacob",
"Gen.29": "Jacob se casa con Lea y Raquel",
"Gen.30": "El ganado de Jacob (método de crianza)",
"Gen.31": "Jacob deja a Labán",
"Gen.32": "Jacob se convierte en Israel",
"Gen.33": "La reunión de Jacob con Esaú",
"Gen.34": "La angustia de Dina",
"Gen.35": "Muere Raquel, muere Isaac",
"Gen.36": "Las generaciones de Esaú",
"Gen.37": "El sueño de José, vendido a Egipto",
"Gen.38": "La vergüenza de Judá",
"Gen.39": "José, Potifar y la prisión",
"Gen.40": "El sueño de José como mayordomo y panadero",
"Gen.41": "José, ministro de agricultura",
"Gen.42": "Los 10 hermanos de José van a Egipto a comprar maíz",
"Gen.43": "Los 11 hermanos de José van a Egipto a comprar maíz",
"Gen.44": "La copa de plata de Benjamín",
"Gen.45": "José lo revela todo",
"Gen.46": "Jacob y su familia se mudan a Egipto",
"Gen.47": "José vende maíz a cambio de tierras para el faraón",
"Gen.48": "Los hijos de José, doble porción",
"Gen.49": "La evaluación que Jacob hace de sus hijos",
"Gen.50": "Los huesos de José (Jacob y José mueren)",
"Exod.1": "La esclavitud en Egipto",
"Exod.2": "El nacimiento de Moisés",
"Exod.3": "La zarza ardiente",
"Exod.4": "Las objeciones de Moisés",
"Exod.5": "El aumento de la esclavitud",
"Exod.6": "Afirmación del pacto abrahámico",
"Exod.7": "Las diez plagas",
"Exod.13": "Guía mediante la columna de nube y fuego",
"Exod.14": "El cruce del Mar Rojo",
"Exod.15": "Incorrecto Tipo de agua (Mara)",
"Exod.16": "Provisión de maná",
"Exod.17": "Situación sin agua (Refidim)",
"Exod.18": "Organización del hombre Jetro",
"Exod.19": "Llegada al monte Sinaí",
"Exod.20": "Entrega de la ley mosaica",
"Exod.32": "Becerro de oro (las tablas de piedra se rompen)",
"Exod.33": "Hacia Canaán (Moisés ve a Dios)",
"Exod.34": "Segundas tablas de piedra",
"Exod.35": "Partes del tabernáculo construidas",
"Exod.40": "Se erige el tabernáculo",
"Lev.1": "Las ofrendas de olor grato - Holocausto",
"Lev.2": "Las ofrendas de olor grato - Ofrenda de harina",
"Lev.3": "Las ofrendas de olor grato - Ofrenda de paz",
"Lev.4": "Las ofrendas de olor no grato - Ofrenda por el pecado",
"Lev.5": "Las ofrendas de olor no grato - Ofrenda por la culpa",
"Lev.6": "Cómo aplicar las cinco ofrendas",
"Lev.8": "Consagración de los sacerdotes",
"Lev.9": "Comienzo del ministerio del sacerdote",
"Lev.10": "Fuego extraño: Nadab y Abiú",
"Lev.11": "La comida de Israel",
"Lev.12": "La ley de la maternidad",
"Lev.13": "¡Lepra!",
"Lev.14": "Purificación de los Leproso",
"Lev.15": "Un Dios Santo, Un Pueblo Santo",
"Lev.16": "El Día de la Expiación",
"Lev.17": "El Significado de la Sangre",
"Lev.18": "Cómo Cae una Nación",
"Lev.21": "El Camino y la Obra de los Sacerdotes",
"Lev.23": "Las Fiestas del Señor",
"Lev.24": "La Maldición y la Pena Capital",
"Lev.25": "La Ley de la Tierra (La Bendición y la Maldición)",
"Lev.26": "Los Cinco Ciclos de la Disciplina",
"Lev.27": "Los Votos, las Primicias, las Dedicaciones, el Diezmo",
"Num.1": "El Censo de las Tribus",
"Num.2": "La Disposición del Campamento",
"Num.10": "El Comienzo de la Marcha (Sinaí a Cades) Barnea)",
"Num.11": "La marcha continúa",
"Num.12": "La murmuración de Miriam y Aarón contra Moisés",
"Num.13": "En Cades: los 12 espías",
"Num.14": "La incredulidad de Israel en Cades",
"Num.15": "El peregrinar por el desierto",
"Num.20": "Situación sin agua #2",
"Num.21": "La serpiente de bronce",
"Num.22": "Balaam y Balac",
"Num.25": "La doctrina de Balaam",
"Num.26": "Se contabiliza la nueva generación",
"Num.27": "Moisés se prepara para morir, Josué es designado",
"Num.28": "Instrucciones sobre las ofrendas",
"Num.30": "La ley de los votos",
"Num.31": "La Juicio sobre Madián",
"Num.32": "Rubén, Gad y la mitad de la tribu de Manasés eligen la tierra al este del Jordán",
"Num.33": "Diario de viaje de 40 años",
"Num.34": "Las fronteras de Canaán",
"Num.35": "Las ciudades de refugio",
"Num.36": "Leyes de herencia (manténgalas en la familia)",
"Deut.1": "Sermón n.° 1 de Moisés",
"Deut.4": "Sermón n.° 2 de Moisés",
"Deut.12": "Sermón n.° 3 de Moisés",
"Deut.28": "Sermón n.° 4 de Moisés",
"Deut.31": "Sermón n.° 5 de Moisés",
"Deut.32": "Cántico y bendición de Moisés",
"Deut.33": "Bendición de Moisés sobre el Tribus",
"Deut.34": "La mirada de Moisés a Canaán, la muerte y el entierro",
"Josh.1": "Josué asume el liderazgo",
"Josh.2": "Rahab y los espías",
"Josh.3": "Cruzando el Jordán",
"Josh.4": "2 memoriales (río Jordán y Gilgal)",
"Josh.5": "El capitán invisible",
"Josh.6": "La conquista de Jericó",
"Josh.7": "Derrota en Hai",
"Josh.8": "Victoria en Hai",
"Josh.9": "Engaño de los gabaonitas",
"Josh.10": "Campaña de Gabaón y campaña del sur",
"Josh.11": "Conquista final de Canaán",
"Josh.12": "Los 31 reyes",
"Josh.13": "División de la tierra",
"Josh.18": "El tabernáculo en Silo",
"Josh.19": "Continúa la división de la tierra Tierra",
"Josh.20": "Las ciudades de refugio",
"Josh.21": "Continúa la división de la tierra (levitas)",
"Josh.22": "Altar rival y cismático de Rubén y Gad",
"Josh.23": "Últimos consejos de Josué",
"Josh.24": "Muerte de Josué",
"Judg.1": "Capítulo “Ni lo hizo”",
"Judg.2": "Institución de los jueces",
"Judg.3": "Señores, enciendan sus motores (los jueces comienzan a gobernar)",
"Judg.4": "Débora y Barac",
"Judg.5": "Cántico de Débora y Barac",
"Judg.6": "Gedeón y el vellón",
"Judg.7": "Victoria de Gedeón, 300 sobre Madián",
"Judg.8": "1. Celos de Efraín; Muerte de Gedeón",
"Judg.9": "El falso rey Abimelec",
"Judg.10": "La maldad de Israel",
"Judg.11": "Jefté, el noveno juez",
"Judg.12": "Segundo celos de Efraín",
"Judg.13": "Los padres de Sansón",
"Judg.14": "El enigma de Sansón",
"Judg.15": "Los actos poderosos de Sansón",
"Judg.16": "Sansón y Dalila",
"Judg.17": "El embrollo de Miqueas",
"Judg.18": "La invasión danita y la idolatría",
"Judg.19": "El levita y su concubina",
"Judg.20": "La tribu de Benjamín casi Destruida",
"Judg.21": "Cómo conseguir una esposa",
"Ruth.1": "Rut y Noemí regresan a Judá desde Moab",
"Ruth.2": "Rut cosecha en los campos de Booz",
"Ruth.3": "Rut y la ley del pariente redentor",
"Ruth.4": "Rut se casa con Booz",
"1Sam.1": "Ana y el nacimiento de Samuel",
"1Sam.2": "Samuel, Elí, los hijos malvados de Elí",
"1Sam.3": "El llamado de Samuel",
"1Sam.4": "Derrota, el Arca se pierde ante los filisteos",
"1Sam.5": "Dagón contra el Arca",
"1Sam.6": "El Arca regresa",
"1Sam.7": "El Arca en casa",
"1Sam.8": "Israel exige una Rey",
"1Sam.9": "Saúl elegido",
"1Sam.10": "La unción de Saúl",
"1Sam.11": "La victoria de Saúl",
"1Sam.12": "Discurso de despedida de Samuel",
"1Sam.13": "El rechazo de Saúl por parte de Dios",
"1Sam.14": "La victoria de Jonatán sobre los filisteos",
"1Sam.15": "La mentira de las ovejas de Saúl",
"1Sam.16": "David elegido y ungido",
"1Sam.17": "David y Goliat",
"1Sam.18": "David y Jonatán",
"1Sam.19": "David huye de Saúl",
"1Sam.20": "Jonatán protege a David",
"1Sam.21": "David sigue huyendo",
"1Sam.22": "La unción de David Hombres valientes",
"1Sam.23": "Las aventuras de los hombres valientes de David",
"1Sam.24": "David perdona la vida a Saúl #1",
"1Sam.25": "Samuel muere",
"1Sam.26": "David perdona la vida a Saúl #2",
"1Sam.27": "David se desvía de su camino en Filistea",
"1Sam.28": "Saúl y la bruja de Endor",
"1Sam.29": "David y Aquis",
"1Sam.30": "David y Siclag (2 esposas capturadas)",
"1Sam.31": "La muerte de Saúl",
"2Sam.1": "La muerte de Saúl y Jonatán contada a David",
"2Sam.2": "Guerra civil: Abner contra David",
"2Sam.3": "Guerra civil: la casa de Saúl contra David",
"2Sam.4": "El asesinato de Is-boset",
"2Sam.5": "David se convierte en rey de Israel",
"2Sam.6": "Arca a Jerusalén",
"2Sam.7": "Se declara el pacto davídico",
"2Sam.8": "David, el poderoso conquistador",
"2Sam.9": "David y Mefiboset",
"2Sam.10": "La guerra entre los amonitas y los sirios",
"2Sam.11": "El pecado de David con Betsabé",
"2Sam.12": "La confesión del pecado de David",
"2Sam.13": "El crimen de Amnón (inmoralidad)",
"2Sam.14": "El hermoso Absalón",
"2Sam.15": "La rebelión de Absalón",
"2Sam.16": "Absalón entra en Jerusalén",
"2Sam.17": "Absalón escucha mentiras Consejeros",
"2Sam.18": "Absalón se cuelga de los cabellos y muere",
"2Sam.19": "David se pone manos a la obra",
"2Sam.20": "La rebelión de Seba",
"2Sam.21": "Tres años de hambruna",
"2Sam.22": "El cántico de liberación de David",
"2Sam.23": "Los valientes de David",
"2Sam.24": "David cuenta el pecado",
"1Kgs.1": "David fracasa, Salomón es ungido",
"1Kgs.2": "La muerte de David",
"1Kgs.3": "La oración de Salomón pidiendo sabiduría",
"1Kgs.4": "Salomón obtiene sabiduría",
"1Kgs.5": "El templo de Salomón: su construcción y dedicación",
"1Kgs.9": "La fama y la riqueza de Salomón",
"1Kgs.10": "Salomón y la reina de Saba",
"1Kgs.11": "La reincidencia y la muerte de Salomón (el ascenso de Jeroboam en el norte)",
"1Kgs.12": "La división del reino (Roboam, el hijo de Salomón en el sur)",
"1Kgs.13": "Un Jeroboam malvado",
"1Kgs.14": "Jeroboam y Roboam mueren",
"1Kgs.15": "Abías, Asá, Baasa, Nabad",
"1Kgs.16": "Algunos de los reyes malvados de Israel (Ela, Zimri, Tibni, Omri, Acab)",
"1Kgs.17": "Elías alimentado por cuervos, resurrección del hijo de la viuda",
"1Kgs.18": "Elías contra Baal (Monte Carmelo)",
"1Kgs.19": "Elías y la voz apacible y delicada",
"1Kgs.20": "Acab y la victoria sobre los sirios",
"1Kgs.21": "Acab, Jezabel",
"1Kgs.22": "Micaías, el hombre de convicción de Dios",
"2Kgs.1": "Elías: enfermedad y muerte de Ocozías",
"2Kgs.2": "Elías llevado al cielo",
"2Kgs.3": "Eliseo: derrota del Moabitas",
"2Kgs.4": "El capítulo de los 5 milagros de Eliseo",
"2Kgs.5": "La curación de Naamán",
"2Kgs.6": "Eliseo y el hacha perdida",
"2Kgs.7": "Eliseo: “¡Comerás!”",
"2Kgs.8": "Eliseo predice 7 años de hambruna",
"2Kgs.9": "Jehú, el conductor furioso",
"2Kgs.10": "Juicio sobre los 70 hijos de Acab",
"2Kgs.11": "Un solo heredero: Joás",
"2Kgs.12": "Reparación del templo",
"2Kgs.13": "Muere Eliseo",
"2Kgs.14": "Guerra civil: Israel y Judá",
"2Kgs.15": "Varios reyes de Israel",
"2Kgs.16": "Gobierno de Acaz",
"2Kgs.17": "El cautiverio asirio y por qué",
"2Kgs.18": "El reinado de Ezequías",
"2Kgs.19": "Isaías y Ezequías",
"2Kgs.20": "La prórroga de 15 años de Ezequías y su muerte",
"2Kgs.21": "El malvado rey Manasés",
"2Kgs.22": "Josías: redescubrimiento de la ley",
"2Kgs.23": "Lectura de la Palabra y celebración de la Pascua",
"2Kgs.24": "El cautiverio de Babilonia: 70 años",
"2Kgs.25": "El cautiverio de Babilonia: sitio de Jerusalén",
"1Chr.1": "Genealogías",
"1Chr.10": "La muerte de Saúl",
"1Chr.11": "Los valientes de David",
"1Chr.13": "Uza y los Arca",
"1Chr.14": "David y los árboles de morera",
"1Chr.15": "El regreso del Arca",
"1Chr.16": "David y un salmo",
"1Chr.17": "El pacto davídico",
"1Chr.18": "El poderoso reino de David",
"1Chr.19": "La guerra entre los amonitas y los sirios",
"1Chr.20": "El gigante de los 24 dedos de las manos y los pies",
"1Chr.21": "El pecado de David al contar",
"1Chr.22": "David prepara los materiales para el templo",
"1Chr.23": "Salomón es nombrado rey, organización de los sacerdotes levíticos",
"1Chr.24": "Continúa la organización de Israel",
"1Chr.28": "Consejo final de David, reina Salomón adolescente, muere David",
"2Chr.1": "Salomón y su Sabiduría",
"2Chr.2": "Salomón construye el templo",
"2Chr.5": "El arca se coloca en el templo, la gloria llena el templo",
"2Chr.6": "Salomón dedica el templo",
"2Chr.7": "El Señor está complacido",
"2Chr.8": "La actividad y la riqueza de Salomón",
"2Chr.9": "Salomón y la reina de Saba",
"2Chr.10": "Roboam sobre 2 tribus del sur",
"2Chr.13": "Jeroboam sobre 10 tribus del norte",
"2Chr.14": "El buen rey Asa",
"2Chr.17": "El buen rey Josafat (nótese la alianza impía con Acab)",
"2Chr.21": "El reinado de Joram",
"2Chr.22": "Solo queda un heredero en la línea real de Cristo, Joás",
"2Chr.23": "Reinado de Joás",
"2Chr.25": "Reinado de Amasías",
"2Chr.26": "Reinado de Uzías",
"2Chr.27": "Reinado de Jotán",
"2Chr.28": "Reinado de Acaz",
"2Chr.29": "Reinado de Ezequías",
"2Chr.33": "Reinado de Manasés (55)",
"2Chr.34": "Reinado de Josías",
"2Chr.36": "El cautiverio babilónico",
"Ezra.1": "Decreto de Ciro (restauración del templo)",
"Ezra.2": "El remanente que regresa",
"Ezra.3": "Se colocan los cimientos del templo",
"Ezra.4": "Oposición, carta a Artajerjes, se detiene la obra",
"Ezra.5": "Se responde a la oposición",
"Ezra.6": "Decreto de Darío (se termina el templo)",
"Ezra.7": "Esdras da gracias al Señor",
"Ezra.8": "Se lleva el tesoro al templo",
"Ezra.9": "Matrimonios impíos (mixtos), la oración de Esdras",
"Ezra.10": "Se juzga el pecado mencionado y se hace la restitución",
"Neh.1": "Los muros en ruinas",
"Neh.2": "Nehemías inspecciona las ruinas",
"Neh.3": "Los constructores comiencen a construir",
"Neh.4": "Oposición en la reconstrucción",
"Neh.7": "Genealogías",
"Neh.8": "Predicación expositiva de Esdras",
"Neh.9": "Repaso de la historia del Antiguo Testamento",
"Neh.10": "Aplicación de la enseñanza a la experiencia",
"Neh.11": "Distribución geográfica de los habitantes de Israel",
"Neh.12": "Dedicación de los muros",
"Neh.13": "La ley y la separación",
"Esth.1": "La reina Vasti desobedece al rey",
"Esth.2": "La reina Ester la judía",
"Esth.3": "Mardoqueo y Amán",
"Esth.4": "Exterminio planificado de la nación judía",
"Esth.5": "“Si perezco, perezco”",
"Esth.6": "Amán Avergonzado",
"Esth.7": "Amán ahorcado",
"Esth.8": "Los judíos liberados",
"Esth.9": "La fiesta de Purim (celebración de la liberación judía)",
"Esth.10": "Mardoqueo, el número 2 en el Reino",
"Job.1": "Job y el sufrimiento (familiar)",
"Job.2": "Job y el sufrimiento (personal)",
"Job.4": "El primer proceso contra Elifaz",
"Job.6": "La defensa de Job",
"Job.8": "El primer proceso contra Bildad",
"Job.9": "La defensa de Job",
"Job.11": "El primer proceso contra Zofar",
"Job.12": "La defensa de Job",
"Job.15": "El segundo proceso contra Elifaz",
"Job.16": "La defensa de Job",
"Job.18": "Segunda acusación contra Bildad",
"Job.19": "La defensa de Job",
"Job.20": "Los argumentos finales de Zofar",
"Job.21": "La defensa de Job",
"Job.22": "Los argumentos finales de Elifaz",
"Job.23": "La defensa de Job",
"Job.25": "Los argumentos finales de Bildad",
"Job.26": "La defensa de Job",
"Job.32": "El discurso de Eliú",
"Job.38": "Dios habla con Job",
"Job.42": "Las confesiones y la restauración de Job",
"Ps.1": "El hombre bendecido",
"Ps.2": "El rey rechazado pero que llega a reinar",
"Ps.3": "Un salmo en Angustia",
"Ps.4": "Oración en la angustia",
"Ps.5": "Compartiendo la actitud de Dios hacia el pecado",
"Ps.6": "Orando en la más profunda angustia",
"Ps.7": "El salmo del santo calumniado",
"Ps.8": "El Hijo del Hombre reinando",
"Ps.9": "Alabanza por el juicio justo",
"Ps.10": "Salmo sobre los malvados",
"Ps.11": "El salmo de los firmes",
"Ps.12": "Mentirosos contra la verdad",
"Ps.13": "El salmo “¿Hasta cuándo?”",
"Ps.14": "El salmo del necio",
"Ps.15": "El regenerado descrito",
"Ps.16": "Muerte y resurrección",
"Ps.17": "Una oración de David contra los malvados",
"Ps.18": "Salmo de liberación de David",
"Ps.19": "El testimonio de la creación y la revelación",
"Ps.20": "Salmo para un día de angustia",
"Ps.21": "Salmo del Rey victorioso",
"Ps.22": "El Buen Pastor (Crucificado)",
"Ps.23": "El Gran Pastor (Resucitado)",
"Ps.24": "El Pastor Príncipe (Ven)",
"Ps.25": "Confianza en medio de la angustia",
"Ps.26": "Cómo evitar la reincidencia",
"Ps.27": "Un deseo en tiempos de angustia",
"Ps.28": "Un clamor por el juicio",
"Ps.29": "La tormenta del juicio",
"Ps.30": "Salmo de Dedicación",
"Ps.31": "Salmo de angustia y confianza",
"Ps.32": "Testimonio de confesión de David",
"Ps.33": "Alabanza por la creación, la providencia y la gracia",
"Ps.34": "Aprecio por la liberación",
"Ps.35": "Oración por los intercesores",
"Ps.36": "Contraste entre el camino malo y el camino de Dios",
"Ps.37": "Salmo “No te impacientes”",
"Ps.38": "David, fuera de la comunión, entra al final",
"Ps.39": "Oración por la sabiduría",
"Ps.40": "La obediencia de Cristo, cántico nuevo",
"Ps.41": "Traición profetizada por Judas Salmo “Espera en Dios”",
"Ps.43": "Los enemigos molestan Yo",
"Ps.44": "Sufrimiento inmerecido",
"Ps.45": "Salmo de la boda real",
"Ps.46": "Triunfo en el período de la gran tribulación",
"Ps.47": "El Señor reina",
"Ps.48": "Jerusalén",
"Ps.49": "La locura de la incredulidad",
"Ps.50": "La naturaleza de la verdadera adoración",
"Ps.51": "El pecado de David reconocido",
"Ps.52": "Salmo del “olivo verde”",
"Ps.53": "El salmo del necio (igual que el Salmo 14)",
"Ps.54": "Salmo del “ayudante mío”",
"Ps.55": "Escape de la tribulación",
"Ps.56": "Una oración del perseguido",
"Ps.57": "Refugio en problemas",
"Ps.58": "Salmo imprecatorio",
"Ps.59": "Oración por liberación y juicio",
"Ps.60": "De la derrota a la victoria",
"Ps.61": "Refugio en la roca",
"Ps.62": "Confianza en Dios la Roca",
"Ps.63": "Salmo “más hermoso”",
"Ps.64": "Los malvados contra los justos",
"Ps.65": "Salmo de acción de gracias",
"Ps.66": "Salmo digno de adoración",
"Ps.67": "Bendición futura del reino",
"Ps.68": "Procesión victoriosa de Dios",
"Ps.69": "Los sufrimientos de Cristo",
"Ps.70": "Salmo conmemorativo",
"Ps.71": "Salmo del santo anciano",
"Ps.72": "El rey y el reino",
"Ps.73": "Envidioso de la prosperidad del Malvado",
"Ps.74": "El enemigo en posesión",
"Ps.75": "La copa del juicio del Señor",
"Ps.76": "Cuando Dios reina en Sión",
"Ps.77": "El santo atribulado",
"Ps.78": "La historia de la gracia de Dios con Israel",
"Ps.79": "¡Una oración con Jerusalén en ruinas!",
"Ps.80": "Cristo, el hombre fuerte",
"Ps.81": "Dios desnuda el corazón",
"Ps.82": "Dios es el juez",
"Ps.83": "¡Afligidos para aprender!",
"Ps.84": "Salmo “Hijos de la gracia”",
"Ps.85": "Salmo “Oración de avivamiento”",
"Ps.86": "Oración de pobres y necesitados",
"Ps.87": "Un cántico de Sión",
"Ps.88": "Salmo de la “más profunda angustia”",
"Ps.89": "Pacto davídico”",
"Ps.90": "Salmo de la muerte (primer Adán)",
"Ps.91": "Salmo de la vida (último Adán)",
"Ps.92": "Palma sabática (de descanso)",
"Ps.93": "El Rey y su trono",
"Ps.94": "Una oración de venganza",
"Ps.95": "Un salmo de alabanza y advertencia",
"Ps.96": "Alabanza y testimonio en vista de la segunda venida",
"Ps.97": "Salmo “El Señor reina”",
"Ps.98": "Un nuevo cántico de victoria",
"Ps.99": "Juicio justo y temblor",
"Ps.100": "Los cien años (Acción de gracias)",
"Ps.101": "El rey y sus súbditos",
"Ps.102": "Una oración en humillación",
"Ps.103": "Salmo “Bendice, alma mía, al Señor”",
"Ps.104": "La alabanza de sus obras",
"Ps.105": "La historia de Israel y la misericordia de Dios",
"Ps.106": "El fracaso de Israel y la gracia de Dios",
"Ps.107": "Acción de gracias por la aflicción",
"Ps.108": "Alabanza por la victoria",
"Ps.109": "Salmo “Poder satánico”",
"Ps.110": "Cristo como Rey y Sacerdote",
"Ps.111": "Salmo “Reverendo es su nombre”",
"Ps.112": "El plan de Dios es mayor que las presiones de Vida",
"Ps.113": "De muladar a gobernante",
"Ps.114": "Cuando Israel salió de Egipto",
"Ps.115": "Dios comparado con los ídolos",
"Ps.116": "Salmo de la “gracia moribunda”",
"Ps.117": "El salmo más corto (alabanza)",
"Ps.118": "El Cristo exaltado",
"Ps.119": "Salmo “La Palabra de Dios”",
"Ps.120": "Oración contra la lengua mentirosa",
"Ps.121": "El salmo del viajero",
"Ps.122": "Jerusalén y la paz",
"Ps.123": "Esperando en la fe",
"Ps.124": "El Señor de nuestro lado",
"Ps.125": "Seguridad para el Confianza",
"Ps.126": "Salmo de libertad",
"Ps.127": "Seguridad en el Señor",
"Ps.128": "Bendiciones terrenales",
"Ps.129": "Consuelo en la aflicción",
"Ps.130": "¿Quién se mantendrá en pie?",
"Ps.131": "Confianza infantil",
"Ps.132": "Salmo del pacto davídico",
"Ps.133": "Salmo de compañerismo",
"Ps.134": "Adoración nocturna",
"Ps.135": "Salmo de alabanza sacerdotal",
"Ps.136": "Su misericordia perdura para siempre",
"Ps.137": "Llanto de cautiverio de Babilonia",
"Ps.138": "Salmo “Engrandeció tu palabra sobre tu nombre”",
"Ps.139": "Salmo de vida espiritual",
"Ps.140": "Oposición del mal",
"Ps.141": "Salmo “Guarda mis palabras”",
"Ps.142": "Salmo del prisionero",
"Ps.143": "Una oración por misericordia en la persecución",
"Ps.144": "Salmo de fuerza militar",
"Ps.145": "Salmo de alabanza pura",
"Ps.146": "Alabanza y confianza",
"Ps.147": "Alabanza por la gracia de Dios a Israel",
"Ps.148": "Alabanza de toda la creación",
"Ps.149": "Un nuevo cántico de alabanza",
"Ps.150": "Alabad al Señor",
"Prov.1": "Introducción a la sabiduría",
"Prov.2": "Buscad la doctrina bíblica “De todo corazón”",
"Prov.3": "Elaboración de la doctrina bíblica",
"Prov.5": "El amor ilegítimo condenado",
"Prov.8": "Mujeres buenas contra mujeres malas",
"Prov.10": "Aplicación de la doctrina bíblica a la experiencia",
"Prov.25": "Proverbios sobre el necio",
"Prov.30": "Palabras de Agur",
"Prov.31": "Una mujer virtuosa",
"Eccl.1": "Nada satisface al creyente carnal",
"Eccl.2": "Los placeres y el materialismo no satisfacen",
"Eccl.3": "El egoísmo no satisface",
"Eccl.5": "La religión vacía y la riqueza no satisfacen",
"Eccl.7": "Las obras humanitarias no satisfacen",
"Eccl.12": "Vuelve a la comunión y camina con el Señor",
"Song.1": "Conversación entre la mujer sulamita y las hijas de Jerusalén",
"Song.2": "Los pensamientos de la sulamita sobre su amante pastor",
"Song.3": "La búsqueda de la mujer por su amante, su deseo de casarse con él, un vistazo del amante rival Salomón en toda su gloria",
"Song.4": "El cortejo del rey Salomón, ella dice que no",
"Song.5": "La mujer Pensamientos acerca de su amante pastor",
"Song.6": "Salomón corteja, ella se niega",
"Song.7": "La mujer sulamita escapa",
"Song.8": "La amante sulamita y el amante pastor juntos nuevamente en su ciudad natal",
"Isa.1": "La terrible maldad de Judá",
"Isa.2": "Avance de la era milenial",
"Isa.5": "Canción fúnebre en la viña",
"Isa.6": "El llamado de Isaías",
"Isa.7": "El capítulo del nacimiento virginal",
"Isa.8": "Maher-shalal-hash-baz",
"Isa.9": "Los nombres de Cristo profetizados",
"Isa.10": "El avance asirio",
"Isa.11": "La rama y el reino milenial",
"Isa.13": "La caída de Babilonia y Filistea",
"Isa.15": "Moab",
"Isa.17": "Damasco",
"Isa.18": "Etiopía",
"Isa.19": "Egipto",
"Isa.20": "Egipto y Etiopía, Babilonia, Edom, Arabia",
"Isa.22": "Jerusalén",
"Isa.23": "Tiro",
"Isa.24": "Problemas tribulacionales",
"Isa.25": "Misericordias milenarias",
"Isa.26": "“Lo guardarás en perfecta paz”",
"Isa.27": "Israel reagrupado",
"Isa.28": "Denunciando a Samaria y Jerusalén",
"Isa.29": "Asedio inminente de Jerusalén",
"Isa.30": "Alianza de Judá con Egipto",
"Isa.32": "Preparación para el Armagedón",
"Isa.35": "La reunión de Israel (2.º advenimiento)",
"Isa.36": "El ejército asirio es derrotado",
"Isa.38": "La enfermedad y la muerte de Ezequías",
"Isa.40": "Palabras de consuelo",
"Isa.45": "La profecía de Ciro",
"Isa.46": "La caída de Babilonia",
"Isa.49": "El gran libertador: Dios",
"Isa.58": "Comparación entre los fieles y los infieles",
"Isa.60": "El glorioso Redentor, Jerusalén y sus ciudadanos",
"Isa.63": "Arrepentimiento y confesión",
"Isa.65": "Nuevos cielos y nueva tierra",
"Jer.1": "El llamado del profeta",
"Jer.2": "La apostasía de Israel",
"Jer.3": "Judá es peor que ¡Israel!",
"Jer.4": "Se acerca la desolación de Judá",
"Jer.5": "Depravación universal de Judá",
"Jer.6": "Destrucción desde el norte (profética)",
"Jer.7": "El arrepentimiento, su única esperanza",
"Jer.8": "La cosecha ha pasado",
"Jer.9": "Jeremías, el profeta lloroso",
"Jer.10": "Jehová, el Dios verdadero",
"Jer.11": "El pacto roto: la muerte de Jeremías planeada",
"Jer.12": "La queja de Jeremías",
"Jer.13": "El cinturón arruinado",
"Jer.14": "La sequía y la intercesión de Jeremías",
"Jer.16": "Se le prohíbe a Jeremías casarse",
"Jer.17": "El sábado profanado, juicio Inevitable",
"Jer.18": "El barro del alfarero",
"Jer.19": "La vasija de barro rota",
"Jer.20": "Jeremías encarcelado, desanimado",
"Jer.21": "El asedio comienza",
"Jer.22": "Advertencia al rey Joacim",
"Jer.23": "Falsos profetas",
"Jer.24": "Las dos canastas de higos",
"Jer.25": "Se predicen 70 años de cautiverio",
"Jer.26": "El juicio de Jeremías ante los príncipes",
"Jer.27": "Yugo de bueyes sobre el cuello de Jeremías",
"Jer.29": "La carta de Jeremías a los exiliados",
"Jer.30": "La gran tribulación",
"Jer.31": "El nuevo pacto",
"Jer.32": "Naturaleza del Nuevo Pacto",
"Jer.34": "Proclamación de libertad de Sedequías",
"Jer.35": "La obediencia de los recabitas",
"Jer.36": "El rey arroja el libro de Jeremías al fuego",
"Jer.37": "El encarcelamiento de Jeremías",
"Jer.39": "Jerusalén quemada",
"Jer.40": "Gedalías nombrado gobernador",
"Jer.42": "El remanente va a Egipto",
"Jer.44": "La apelación final de Jeremías",
"Jer.45": "Baruc (el escriba de Jeremías)",
"Jer.46": "Profecía contra Egipto",
"Jer.47": "Profecía contra los filisteos",
"Jer.48": "Profecía contra Moab",
"Jer.49": "Profecía contra Amón, Edom, Siria, Hazor, Elam",
"Jer.50": "Predicción de la caída de Babilonia",
"Jer.52": "La salvación venidera del Señor",
"Lam.1": "La partida de Judá",
"Lam.2": "La devastación de Jehová",
"Lam.3": "El discernimiento de Jeremías",
"Lam.4": "La disciplina de Jehová",
"Lam.5": "La fuerza disuasoria para Judá",
"Ezek.1": "La visión de la gloria de Dios",
"Ezek.2": "La voz de Dios",
"Ezek.4": "El asedio simbólico de Jerusalén",
"Ezek.8": "La visión de Ezequiel: viaje a Jerusalén",
"Ezek.12": "Ezequiel se muda con sus enseres domésticos",
"Ezek.13": "Falsos profetas",
"Ezek.14": "Investigadores hipócritas",
"Ezek.15": "La parábola de la vid",
"Ezek.16": "Alegoría de la La esposa infiel",
"Ezek.17": "La parábola de las dos águilas",
"Ezek.18": "El alma que pecare, esa morirá",
"Ezek.19": "La lamentación final",
"Ezek.20": "La inmundicia de la idolatría",
"Ezek.21": "El canto de la espada",
"Ezek.22": "Los pecados de Jerusalén",
"Ezek.23": "Aholá y Aholiba",
"Ezek.24": "La olla hirviente",
"Ezek.25": "Amón, Moab, Edom, Filistea",
"Ezek.26": "Tiro y Sidón",
"Ezek.29": "Egipto (seis visiones)",
"Ezek.33": "El centinela",
"Ezek.34": "Los pastores",
"Ezek.35": "Confirmada la condenación de Edom",
"Ezek.36": "Confirmada la Nueva Alianza",
"Ezek.37": "El Valle de los Huesos Secos",
"Ezek.38": "Gog y Magog",
"Ezek.40": "El Templo Milenial",
"Ezek.44": "La Adoración Milenial",
"Ezek.47": "La Tierra Milenial",
"Dan.1": "La Sabiduría de Daniel",
"Dan.2": "La Imagen del Sueño",
"Dan.3": "El Horno Ardiente",
"Dan.4": "La Visión del Árbol de Nabucodonosor",
"Dan.5": "Belsasar y la Escritura en la Pared",
"Dan.6": "Daniel en el Foso de los Leones",
"Dan.7": "La Visión de las Cuatro Bestias",
"Dan.8": "La Visión del Carnero y el Macho Cabrío",
"Dan.9": "La Visión de Daniel 70 semanas",
"Dan.10": "El conflicto angélico",
"Dan.11": "El hombre de pecado",
"Dan.12": "El tiempo del fin",
"Hos.1": "La esposa y los hijos de Oseas",
"Hos.4": "Efraín se une a los ídolos",
"Hos.5": "Efraín se convertirá en una ruina",
"Hos.6": "Los sacerdotes asesinan y cometen lascivia",
"Hos.7": "Todos son adúlteros",
"Hos.8": "Sembraron viento, segarán torbellino",
"Hos.9": "Abominables como los ídolos que aman",
"Hos.10": "La gloria de Betel se ha ido",
"Hos.11": "¿Cómo te abandonaré?",
"Hos.12": "Jacob encontró a Dios en Betel",
"Hos.13": "Pecan cada vez más",
"Hos.14": "Israel volverá a Dios",
"Joel.1": "La plaga de langostas 2. El venidero día del Señor",
"Joel.3": "Grandes acontecimientos del día del Señor",
"Amos.1": "Juicios sobre las naciones vecinas",
"Amos.3": "Los lujosos palacios de Samaria",
"Amos.4": "“Prepárate para encontrarte con tu Dios”",
"Amos.5": "El día del Señor",
"Amos.6": "El cautiverio asirio",
"Amos.7": "Tres visiones de destrucción (langostas, fuego, plomada)",
"Amos.8": "La cesta de frutas de verano",
"Amos.9": "La futura bendición del reino de Israel restaurado",
"Obad.1": "El juicio de Edom, Restauración de Israel",
"Jonas.1": "La huida de Jonás",
"Jonas.2": "La oración de Jonás",
"Jonas.3": "El arrepentimiento de Nínive",
"Jonas.4": "El disgusto de Jonás",
"Mic.1": "Samaria condenada",
"Mic.2": "Brutalidad de los gobernantes",
"Mic.4": "Profecía del reino milenial",
"Mic.5": "Profecía del nacimiento de Cristo",
"Mic.6": "La controversia de Jehová con su pueblo",
"Mic.7": "Desolación, pero Dios triunfará",
"Nah.1": "Nínive será juzgada",
"Nah.2": "El juicio se ejecuta",
"Nah.3": "Más razones por las que",
"Hab.1": "Las dos profecías del profeta Diálogos con Dios",
"Hab.3": "La oración y alabanza del profeta",
"Zeph.1": "El juicio de Dios sobre Judá",
"Zeph.2": "El juicio de Dios sobre las naciones vecinas",
"Zeph.3": "Bendiciones milenarias en Israel",
"Hag.1": "Dos mensajes: reprensión y elogio",
"Hag.2": "Tres mensajes: aliento, bendición y destrucción del poder gentil",
"Zech.1": "Ocho visiones nocturnas",
"Zech.6": "La coronación de Josué",
"Zech.7": "Pregunta sobre el ayuno",
"Zech.9": "El juicio de Dios sobre las naciones vecinas",
"Zech.12": "Segunda llegada y aceptación del Mesías como Rey",
"Mal.1": "Sacerdotes: vuelvan a la Compañerismo",
"Mal.2": "Sacerdotes y pueblo: vuelvan a la comunión",
"Mal.3": "Robo, pero bendición futura",
"Mal.4": "La segunda venida",
"Matt.1": "Genealogía de Cristo",
"Matt.2": "Infante; Niño; y Herodes",
"Matt.3": "Juan el Bautista y Jesús",
"Matt.4": "Tentación y Proclamación",
"Matt.5": "Sermón del Monte",
"Matt.8": "Milagros: Leproso; Paralítico; Fiebre; Viento y Mar; Demonios",
"Matt.9": "Milagros: Paralítico; Publicano; Hija Muerta; Enfermedad; Demonios",
"Matt.10": "Discípulos son Enseñados y Enviados",
"Matt.11": "Juan en Prisión; Mi Yugo",
"Matt.12": "Fariseos Critican; Jonás Señala",
"Matt.13": "Parábolas del Reino de los Cielos",
"Matt.14": "Panes; Peces; Caminar sobre el Agua",
"Matt.15": "Lavar Manos",
"Matt.16": "Levadura; Llaves; Hacia Jerusalén",
"Matt.17": "Transfiguración",
"Matt.18": "Niños; Perdón",
"Matt.19": "Divorcio; Hombre rico",
"Matt.20": "Propietario; Jesús se acerca a Jerusalén",
"Matt.21": "Jesús entra en Jerusalén",
"Matt.22": "Banquete de bodas; Fariseos y escribas silenciados",
"Matt.23": "Ay de los escribas, fariseos y Jerusalén",
"Matt.24": "Señal de la venida de Jesús; Señal del fin",
"Matt.25": "El regreso de Cristo; Juzga a las naciones",
"Matt.26": "Cena; Arresto; Juicios",
"Matt.27": "Juicios; Cruz",
"Matt.28": "Resurrección; Comisión",
"Mark.1": "El bautismo de Jesús, la tentación y los primeros años de su ministerio",
"Mark.2": "Jesús sana y perdona al paralítico; Leví",
"Mark.3": "La autoridad de Jesús sobre la enfermedad y los demonios; llama a sus discípulos",
"Mark.4": "El sembrador y la semilla de mostaza; el poder de Jesús sobre la tormenta",
"Mark.5": "La autoridad de Jesús sobre los cerdos, los demonios, la enfermedad y la muerte",
"Mark.6": "Jesús envía a sus discípulos de dos en dos; recuerdo de Herodes; alimenta a 5000",
"Mark.7":
"Las tradiciones de los fariseos sobre las Escrituras; la mujer sirofenicia; el sordomudo",
"Mark.8": 'Jesús alimenta a los 4000; Pedro dijo "Tú eres el Cristo"',
"Mark.9": "La transfiguración; Jesús predice su muerte y resurrección",
"Mark.10": 'Divorcio; hijos; "para los hombres la salvación es imposible"',
"Mark.11": "Jesús entra en Jerusalén y maldice la higuera",
"Mark.12":
"Viña; impuestos; resurrección; el mandamiento principal; Hijo de David; orgullo; dar",
"Mark.13": "Acontecimientos en torno al regreso de Jesús a la tierra",
"Mark.14": "Última cena de Pascua; arresto; juicios ilegales; fracaso de Pedro",
"Mark.15": "Pilato interroga a Jesús; los judíos lo crucifican",
"Mark.16": "Jesús resucitó de entre los muertos",
"Luke.1": "Los ángeles anuncian dos nacimientos; nace Juan; Zacarías profetiza",
"Luke.2": "Nacimiento, dedicación y primeros 12 años de Jesús",
"Luke.3": "Juan bautiza a Jesús; La genealogía de Jesús",
"Luke.4":
"La tentación de Jesús; el poder del Espíritu Santo; el ministerio público de Jesús",
"Luke.5": "La captura de hombres; la curación de enfermos; Leví",
"Luke.6": "Jesús llama a los doce y luego enseña el sermón",
"Luke.7": "La fe del centurión; la pregunta de Juan; el perfume",
"Luke.8": "El sembrador; la tormenta y la fe; los demonios y los cerdos; la hija de Jairo",
"Luke.9":
"Jesús envía a los doce; alimenta a 5000; la transfiguración; los demonios; los discípulos",
"Luke.10": "Jesús envía a los setenta; el buen samaritano; Marta",
"Luke.11": "El Padre Nuestro; el reino dividido; Jonás",
"Luke.12": "La levadura de los fariseos; los gorriones; los graneros; los mayordomos dispuestos",
"Luke.13": "Arrepentíos o juicio; el reino de Dios",
"Luke.14": "Trampa del sábado; autopromoción; hospitalidad; mis discípulos",
"Luke.15": "Cien ovejas; diez monedas; dos hijos",
"Luke.16": "El mayordomo despedido; los fariseos; Lázaro",
"Luke.17": "Ojal; diez leprosos; días de Noé",
"Luke.18":
"Oración persistente; dos hombres; niños; joven gobernante; Jesús predice su muerte",
"Luke.19": "Zaqueo; el noble; Jesús entra en Jerusalén",
"Luke.20":
"Los líderes religiosos desafían la autoridad de Jesús; viticultores; César; resurrección; David",
"Luke.21":
"Jesús predice persecución; destrucción de Jerusalén; tribulación; segunda venida; higuera",
"Luke.22": "Pascua del Señor; arresto; Pedro; pruebas",
"Luke.23": "Crucifixión después de más pruebas; sepultura",
"Luke.24": "Resurrección; Jesús en el Antiguo Testamento; ascensión",
"John.1": "La Palabra Viva de Dios",
"John.2": "Bodas de Caná",
"John.3": "Nicodemo",
"John.4": "Mujer Samaritana",
"John.5": "Cojo Sanado",
"John.6": "Pan de Vida",
"John.7": "Ríos de Agua Viva",
"John.8": "Descendientes de Abraham",
"John.9": "Ciego Sanado",
"John.10": "Rebaño-Pastor",
"John.11": "Lázaro",
"John.12": "Entrada a Jerusalén",
"John.13": "Lavado de Pies",
"John.14": "Camino-Verdad-Vida",
"John.15": "Vid-Ramos",
"John.17": "Cristo Partirá",
"John.18": "Arresto y Juicios",
"John.19": "Muerte por los pecados",
"John.20": "Resurrección",
"John.21": "Mar de Tiberio",
"Acts.1": "Cristo asciende, los discípulos esperan",
"Acts.2": "Pentecostés",
"Acts.3": "Un cojo es sanado",
"Acts.4": "La primera persecución",
"Acts.5": "Ananías y Safira",
"Acts.6": "Los primeros diáconos",
"Acts.7": "Esteban y el martirio",
"Acts.8": "Felipe y el eunuco",
"Acts.9": "La conversión de Saulo en el camino a Damasco",
"Acts.10": "Pedro y Cornelio",
"Acts.11": "Pedro reivindica su ministerio a los gentiles",
"Acts.12": "Santiago asesinado, Pedro liberado",
"Acts.13": "El primer viaje de Pablo (a Pisidia) Antioquía)",
"Acts.14": "Primer viaje (Pablo apedreado)",
"Acts.15": "Concilio de Jerusalén",
"Acts.16": "Segundo viaje (Filipos)",
"Acts.17": "Segundo viaje (Tesalónica, Berea, Atenas)",
"Acts.18": "Segundo viaje (Corinto)",
"Acts.19": "Tercer viaje (Éfeso)",
"Acts.20": "Tercer viaje (Mileto)",
"Acts.21": "Tercer viaje (Arresto en Jerusalén)",
"Acts.22": "Defensa de Pablo ante las multitudes",
"Acts.23": "Defensa ante el Sanedrín",
"Acts.24": "Ante Félix",
"Acts.25": "Ante Festo",
"Acts.26": "Ante el rey Agripa",
"Acts.27": "Naufragio",
"Acts.28": "Malta y Roma",
"Rom.1": "Todos los gentiles bajo pecado",
"Rom.2": "Todos los judíos bajo pecado",
"Rom.3": "Todos han pecado",
"Rom.4": "Justificación por la fe",
"Rom.6": "El caminar cristiano",
"Rom.9": "Israel en profecía",
"Rom.10": "Israel en fracaso",
"Rom.11": "Israel en éxito",
"Rom.12": "Sacrificio vivo",
"Rom.13": "Ama a tu prójimo",
"Rom.14": "Discernir a los dudosos",
"Rom.15": "Judíos y gentiles, uno en Cristo",
"Rom.16": "La Amigos",
"1Cor.1": "Divisiones",
"1Cor.2": "El hombre natural, carnal y espiritual",
"1Cor.3": "El tribunal de Cristo",
"1Cor.4": "Juzgándonos unos a otros",
"1Cor.5": "La inmoralidad reprendido",
"1Cor.6": "Procesos judiciales con cristianos",
"1Cor.7": "Matrimonio cristiano",
"1Cor.8": "Carnes ofrecidas a los ídolos",
"1Cor.9": "Capítulo del náufrago",
"1Cor.10": "El mal ejemplo de Israel",
"1Cor.11": "Conducta en la Cena del Señor",
"1Cor.12": "Dones espirituales",
"1Cor.13": "Capítulo del amor",
"1Cor.14": "Dones espirituales",
"1Cor.15": "Capítulo de la resurrección",
"1Cor.16": "Cierre Instrucciones",
"2Cor.1": "El plan de Pablo de venir a Corinto",
"2Cor.2": "El hombre inmoral es limpiado",
"2Cor.3": "El ministerio glorioso",
"2Cor.4": "El ministerio del sufrimiento",
"2Cor.5": "El ministerio de la reconciliación",
"2Cor.6": "El ministerio separado",
"2Cor.7": "El corazón de Pablo",
"2Cor.8": "El dinero importa",
"2Cor.9": "Dar con alegría",
"2Cor.10": "El punto de vista divino contra el punto de vista humano",
"2Cor.11": "La jactancia de Pablo",
"2Cor.12": "El tercer cielo y la espina",
"2Cor.13": "Observaciones finales",
"Gal.1": "La perversión del evangelio por los falsos maestros",
"Gal.2": "El legalismo contra la gracia",
"Gal.3": "Abrahámico Pacto",
"Gal.4": "La maldición del legalismo",
"Gal.5": "Andar en el Espíritu, fruto del Espíritu (hacia adentro)",
"Gal.6": "Andar en el Espíritu, ministerio a otros (hacia afuera)",
"Eph.1": "La riqueza doctrinal del cristiano",
"Eph.3": "El andar del cristiano",
"Eph.5": "La guerra del cristiano",
"Phil.1": "La mente de Pablo",
"Phil.2": "La mente de Cristo",
"Phil.3": "Para que yo pueda conocerle",
"Phil.4": "Lo que los creyentes deben pensar",
"Col.1": "Las 7 superioridades de Cristo",
"Col.2": "Dios es completo",
"Col.3": "El fruto de la unión con Cristo",
"Col.4": "Ejemplos piadosos: Tíquico, Onésimo, Epafras",
"1Thess.1": "La obra de Fe, trabajo de amor, firmeza en la esperanza",
"1Thess.2": "Testimonio de Pablo",
"1Thess.3": "Informe de Timoteo a Pablo",
"1Thess.4": "Capítulo del Rapto",
"1Thess.5": "Paz y seguridad, luego destrucción repentina",
"2Thess.1": "Consuelo en la persecución",
"2Thess.2": "El hombre de pecado revelado",
"2Thess.3": "Cristianos desordenados y entrometidos",
"1Tim.1": "El legalismo y la enseñanza errónea reprendidos",
"1Tim.2": "Oración por los líderes gubernamentales",
"1Tim.3": "Calificaciones para pastores y diáconos",
"1Tim.4": "Doctrina de demonios versus buena doctrina",
"1Tim.5": "El ministerio de Viudas",
"1Tim.6": "El cristiano en los negocios",
"2Tim.1": "Loida, Eunice, Timoteo",
"2Tim.2": "Un buen soldado estudia",
"2Tim.3": "Capítulo de inspiración verbal",
"2Tim.4": "El pensamiento de Pablo dos meses antes de morir",
"Titus.1": "Creta y el cristianismo",
"Titus.2": "En busca de esa bienaventurada esperanza",
"Titus.3": "La producción del bien divino",
"Titus.4": "El rechazo de los herejes",
"Phlm.1": "El cristianismo eficaz y rentable",
"Heb.1": "El conflicto angélico: Cristo es mejor que los ángeles",
"Heb.2": "El conflicto angélico: Cristo hecho inferior a los ángeles",
"Heb.3": "Cristo es mejor que Moisés",
"Heb.4": "La técnica de la fe y el descanso",
"Heb.5": "Cristo, nuestro Sumo Sacerdote",
"Heb.6": "Hacia la madurez",
"Heb.7": "Melquisedec contra el Sacerdocio Aarónico",
"Heb.8": "El Nuevo Pacto contra el Pacto Mosaico",
"Heb.9": "La sangre de Cristo",
"Heb.10": "En el Santísimo",
"Heb.11": "El salón de la fe",
"Heb.12": "Capítulo del castigo",
"Heb.13": "Llevar su reproche",
"Jas.1": "Capítulo de pedir sabiduría",
"Jas.2": "Relación entre la fe y las obras",
"Jas.3": "Capítulo de la lengua",
"Jas.4": "La reprensión de la mundanalidad",
"Jas.5": "Consejos prácticos sobre las riquezas, la paciencia y la oración",
"1Pet.1": "La prueba de tu fe es preciosa",
"1Pet.2": "Sufrir a la luz de su sufrimiento",
"1Pet.3": "Cómo ganar a un marido negativo",
"1Pet.4": "Pruebas y sufrimientos extraños",
"1Pet.5": "Servicio cristiano: líderes y pueblo",
"2Pet.1": "La gran y preciosa Promesas",
"2Pet.2": "Falsos maestros",
"2Pet.3": "Quema de los cielos y la tierra actuales",
"1John.1": "Cristo es luz",
"1John.3": "Cristo es amor",
"1John.5": "Cristo es vida",
"2John.1": "Verdad versus error",
"3John.1": "Hospitalidad",
"Jude.1": "Contendiendo por la fe",
"Rev.1": "Introducción",
"Rev.2": "Las siete iglesias",
"Rev.4": "Los cielos se abrieron",
"Rev.5": "Los siete sellos",
"Rev.6": "Los siete sellos se abrieron",
"Rev.7": "Sellado de los 144, las siete trompetas",
"Rev.9": "Las trompetas se abrieron 3ra",
"Rev.10": "El ángel fuerte y el pequeño ángel Libro",
"Rev.11": "Los dos testigos",
"Rev.12": "Los siete personajes",
"Rev.13": "La bestia del mar y la bestia de la tierra",
"Rev.14": "Visión del Cordero y los 144.000",
"Rev.15": "Las siete copas 16: “Las copas abiertas”",
"Rev.17": "Babilonia religiosa",
"Rev.18": "Babilonia comercial",
"Rev.19": "La segunda venida",
"Rev.20": "El gran trono blanco",
"Rev.21": "Los nuevos cielos, la nueva tierra y la nueva Jerusalén",
"Rev.22": "La eternidad",
// BibleBookList 
Gen: "Génesis",
Exod: "Éxodo",
Lev: "Levítico",
Num: "Números",
Deut: "Deuteronomio",
Josh: "Josué",
Judg: "Jueces",
Ruth: "Rut",
"1Sam": "1 Samuel",
"2Sam": "2 Samuel",
"1Kgs": "1 Reyes",
"2Kgs": "2 Reyes",
"1Chr": "1 Crónicas",
"2Chr": "2 Crónicas",
Ezra: "Esdras",
Neh: "Nehemías",
Esth: "Ester",
Job: "Job",
Ps: "Salmos",
Prov: "Proverbios",
Eccl: "Eclesiastés",
Song: "Cantar de los Cantares",
Isa: "Isaías",
Jer: "Jeremías",
Lam: "Lamentaciones",
Ezek: "Ezequiel",
Dan: "Daniel",
Hos: "Oseas",
Joel: "Joel",
Amos: "Amós",
Obad: "Abdías",
Jonah: "Jonás",
Mic: "Miqueas",
Nah: "Nahum",
Hab: "Habacuc",
Zeph: "Sofonías",
Hag: "Hageo",
Zech: "Zacarías",
Mal: "Malaquías",
Matt: "Mateo",
Mark: "Marcos",
Luke: "Lucas",
Acts: "Hechos",
Rom: "Romanos",
"1Cor": "1 Corintios",
"2Cor": "2 Corintios",
Gal: "Gálatas",
Eph: "Efesios",
Phil: "Filipenses",
Col: "Colosenses",
"1Thess": "1 Tesalonicenses",
"2Thess": "2 Tesalonicenses",
"1Tim": "1 Timoteo",
"2Tim": "2 Timoteo",
Titus: "Tito",
Phlm: "Filemón",
Heb: "Hebreos",
Jas: "Santiago",
"1Pet": "1 Pedro",
"2Pet": "2 Pedro",
"1John": "1 Juan",
"2John": "2 Juan",
"3John": "3 Juan",
Jude: "Judas",
Rev: "Apocalipsis",
// enNavTitles
"00-01a": "La creación y Adán",
"00-01b": "Noé y Babel",
"00-01c": "Abraham e Isaac",
"00-01d": "Jacob",
"00-01e": "José",
"00-02a": "Los primeros años de Moisés",
"00-02b": "Salida de Egipto",
"00-02c": "Leyes",
"00-02d": "Sacerdotes y tabernáculo",
"00-02e": "Lev-Num",
"00-02f": "Deut",
"00-02g": "Josué",
"00-03a": "Jueces",
"00-03b": "Rut",
"00-03c": "Samuel (hasta Saúl)",
"00-04a": "Saúl",
"00-04b": "Saúl y David",
"00-04c": "Salmos",
"00-04c2": "Salmos 2",
"00-04d": "Rey David",
"00-04e": "Nacimiento de Salomón - La muerte de David",
"00-04f": "El rey Salomón",
"00-04g": "Los escritos de Salomón",
"00-05a": "Roboam-Elías y Acab",
"00-05b": "Eliseo al exilio1",
"00-05c": "Ezequías - Sedequías (exilio2)",
"00-05d": "Escritos de Isaías y Jeremías",
"00-06a": "Daniel",
"00-06b": "Ezequiel",
"00-06c": "Esdras 1-6",
"00-06d": "Ester",
"00-06e": "Esdras 7-10, Nehemías 8-12",
"00-06f": "Nehemías 1-7,13, Malaquías",
"00-06g": "Oseas, Joel, Abdías, Miqueas",
"00-06h": "Nahum, Habacuc, Sofonías",
"00-07a": "Mateo",
"00-07a-descr": "Cristo como Rey",
"00-07b": "Marcos",
"00-07b-descr": "Cristo como Siervo",
"00-07c": "Lucas",
"00-07c-descr": "Cristo como Hijo del Hombre",
"00-07d": "Juan",
"00-07d-descr": "Cristo como Dios",
"00-08a": "Acts.1-7",
"00-08a-descr": "La Iglesia comienza",
"00-08b": "Acts.8-12",
"00-08b-descr": "La Iglesia se adapta a persecución",
"00-08c": "Acts.13-20",
"00-08c-descr": "Pablo viaja, testifica y enseña",
"00-08d": "Acts.21-28",
"00-08d-descr": "Pablo bajo arresto, pero todavía en servicio",
"00-09a": "Epístolas de Pablo",
"00-09a-descr": "Romanos a 2 Tesalonicenses",
"00-09b": "Epístolas pastorales",
"00-09b-descr": "1 y 2 Timoteo, Tito y Filemón",
"00-09c": "Otras epístolas",
"00-09c-descr": "Hebreos a Judas",
"00-09d": "Apocalipsis",
"00-09d-descr": "El Apocalipsis a Juan",
"00-10a": "Job",
"00-10b": "Salmos, Libro 1",
"00-10b-descr": "Los Salmos Fundacionales",
"00-10c": "Salmos, Libro 2",
"00-10c-descr": "Los Salmos de Liberación",
"00-10d": "Salmos, Libro 3",
"00-10d-descr": "Los Salmos del Santuario",
"00-10e": "Salmos, Libro 4",
"00-10f": "Salmos, Libro 5",
"00-10f-descr": "Los Salmos de Alabanza",
"00-10g": "Proverbios",
"00-10h": "Eclesiastés",
"00-10i": "Cantar de los Cantares",
"000-01": "Génesis",
"000-01-descr": "En el principio",
"000-02": "Éxodo",
"000-02-descr": "Salida de Egipto hasta Josué",
"000-03": "Jueces",
"000-03-descr": "incluida la primera parte de 1 Samuel",
"000-04": "Los primeros 3 reyes",
"000-04-descr": "de Israel - y sus escritos",
"000-05": "Reino dividido",
"000-05-descr": "hasta el comienzo del segundo exilio, incluyendo Isaías y Jeremías",
"000-06": "El exilio",
"000-06-descr": "incluido el regreso del exilio, Ezequiel y los profetas menores",
"000-07": "Evangelios",
"000-07-descr": "Marcos, Mateo, Lucas y Juan",
"000-08": "Hechos",
"000-08-descr": "de los apóstoles",
"000-09": "Epístolas",
"000-09-descr": "incluyendo Apocalipsis",
"000-10": "Libros poéticos",
"000-10-descr": "Salmos, canciones, proverbios y poemas",
"Matt.Choice.1": "Jesús y su reino",
"Matt.Choice.2": "La oposición y el rechazo se acumulan",
"Matt.Choice.3": "La preparación de los discípulos",
"Matt.Choice.4": "La oposición y el rechazo culminan",
"Matt.Choice.5": "Cruz, resurrección y Comisión",
"Mark.Choice.1": "Ministerio público",
"Mark.Choice.2": "Ministerio privado, Arresto, Muerte y Resurrección",
"Luke.Choice.1": "Nace Jesús, Ministerio temprano",
"Luke.Choice.2": "Doctrina, Milagros, Oposición",
"Luke.Choice.3": "La oposición se endurece, Muerte, Resurrección y Ascensión",
"John.Choice.1": "Ministerio público",
"John.Choice.2": "Ministerio privado",
"John.Choice.3": "Cruz y Resurrección",
John: "John",
// enAdditionalText
ChVerseDelimiter: ",",
Chapter: "Capítulo",
newPassage: "Nuevo pasaje",
BeginCh: "Comienzo del capítulo",
BeginV: "Comienzo del versículo",
EndCh: "Fin del capítulo",
EndV: "Fin del versículo",
Verse: "Verso",
JohnLongTitle: "El Evangelio de Juan",
"John.VideoURL.YT": "https://www.youtube.com/watch?v=yGEPSKZJmCA",
"John.ImgId": "img/john-pics/VB-John1v3.jpg",
"John.Descr":
"El Evangelio de Juan comienza con una introducción poética que coloca la historia de Jesús dentro de la historia más amplia de la Palabra de Dios. Una palabra es una forma de comunicación, y la historia enfatiza las formas en que Dios habla al mundo a través de Jesús. \nEste Evangelio nos ayuda a tener una relación de confianza en Dios, como para la que fuimos creados y que es la vida verdadera. \nJesús comunica la voluntad de Dios por las palabras que pronuncia, por los milagros que realiza, por la muerte que muere en amor por los demás y por la resurrección. Los milagros registrados en el evangelio de Juan están escritos para que el lector crea en Jesús y encuentre vida en Su nombre. \nJesús aparece en el papel de un ser humano, lo que significa que es un ejemplo para que otras personas lo sigan. Como ser humano típico, no poseía ningún poder extraordinario que no esté disponible para cualquier otra persona que lo pida y que cumpla las condiciones para recibirlo.",
"John.1.Descr":
"El Verbo de Dios se hizo carne y habitó entre nosotros. Juan el Bautista dio testimonio de él. Andrés se lo dijo a Simón Pedro y siguieron a Jesús.",
"John.2.Descr":
'Jesús convirtió el agua en vino en una boda. Expulsó a los cambistas del templo. Dijo: "Destruyan este templo y lo levantaré."',
"John.3.Descr":
'Jesús le dijo a Nicodemo: "Nace de nuevo. El que cree en el Hijo tendrá vida eterna. Juan el Bautista dijo: «Él está por encima de todos.»',
"John.4.Descr": `Jesús habló con una mujer samaritana acerca de sus maridos. Ella dijo: «¿Será éste el Cristo?» Muchos creyeron. Sanó al hijo de un funcionario.`,
"John.5.Descr":
'Jesús sanó a un hombre en Betesda. Dijo: «El Hijo sólo hace lo que ve hacer al Padre. Mis obras y las Escrituras dan testimonio.»',
"John.6.Descr":
'Jesús alimentó a 5.000 hombres y caminó a través del mar. Dijo: «Yo soy el pan de vida. Mi carne es verdadero alimento. Muchos discípulos se apartaron.',
"John.7.Descr":
'Jesús fue a la fiesta. La gente decía: "¿Es éste el Cristo?" Los sumos sacerdotes intentaron arrestarlo. Él gritó: "Vengan y beban."',
"John.8.Descr":
'Jesús no condenó a una mujer sorprendida en adulterio. Los fariseos lo interrogaron. Él dijo: "Si Dios fuera su Padre, me amarían."',
"John.9.Descr":
'Jesús curó a un ciego en sábado. Los fariseos llamaron al hombre y lo echaron fuera. Jesús dijo: "He venido para que los ciegos vean."',
"John.10.Descr":
"Jesús dijo: 'Yo soy el buen pastor. Yo doy mi vida por las ovejas.' Le preguntaron: «¿Eres tú el Cristo?» Él dijo: «Mis ovejas me siguen».",
"John.11.Descr":
"«Lázaro murió. Jesús fue al sepulcro y dijo: «Lázaro, sal fuera». Lázaro salió. Los sumos sacerdotes conspiraron para dar muerte a Jesús.",
"John.12.Descr":
"«Jesús entró en Jerusalén en caballo. La multitud gritó: «¡Hosanna!». Él dijo: «Es necesario que el Hijo del Hombre sea levantado. Yo he venido a salvar al mundo.",
"John.13.Descr": "«Jesús les lavó los pies a los discípulos. Dijo: «Uno de ustedes me va a entregar». Judas se fue. Jesús dijo: «Amaos los unos a los otros como yo os he amado.",
"John.14.Descr": "«Yo soy el camino, la verdad y la vida. Yo estoy en el Padre y el Padre en mí. Él os dará el Espíritu Santo. No tengan miedo.",
"John.15.Descr":
'"Yo soy la vid, ustedes son los sarmientos. Ustedes son mis amigos si hacen lo que yo les mando. Si me persiguieron a mí, los perseguirán a ustedes."',
"John.16.Descr":
'"El Espíritu convencerá al mundo de pecado. Él los guiará a toda la verdad. Su tristeza se convertirá en alegría. Yo voy al Padre."',
"John.17.Descr":
'Jesús dijo: "Padre, he revelado tu nombre a los que me diste. Santifícalos en la verdad. Que todos los que crean en mí sean uno.',
"John.18.Descr":
'Judas entregó a Jesús a los sumos sacerdotes. Pedro lo negó. Fue enviado ante Pilato. Jesús dijo: "Mi reino no es de este mundo."',
"John.19.Descr":
'Los soldados tomaron a Jesús y lo crucificaron. Él dijo: "Todo está cumplido". Entregó el espíritu. Un soldado le atravesó el costado con una lanza.',
"John.20.Descr":
'María fue al sepulcro y lo encontró vacío. Jesús la encontró. Se acercó y se puso en medio de los discípulos. Tomás dijo: "¡Señor mío y Dios mío!"',
"John.21.Descr":
'Jesús se apareció mientras los discípulos pescaban. Le dijo a Pedro: "¿Me amas? Apacienta mis ovejas". El discípulo amado ha dado testimonio.',
"John.1.1": "El Verbo se hizo carne",
"John.1.19": "Juan el Bautista niega ser el Mesías",
"John.1.29": "Juan da testimonio de Jesús",
"John.1.35": "Los discípulos de Juan siguen a Jesús",
"John.1.43": "Jesús llama a Felipe y Natanael",
"John.2.1": "Jesús convierte el agua en vino",
"John.2.13": "Jesús limpia los atrios del templo",
"John.2.23": "Jesús entiende a la gente",
"John.3.1": "Jesús enseña a Nicodemo",
"John.3.22": "Juan da testimonio de nuevo de Jesús",
"John.4.1": "Jesús habla con una samaritana",
"John.4.27": "Los discípulos se reúnen con Jesús",
"John.4.39": "Muchos samaritanos creen",
"John.4.43": "Jesús sana a un hijo del funcionario",
"John.5.1": "La curación en la piscina",
"John.5.16": "La autoridad del Hijo",
"John.5.19": "La autoridad de Jesús: la autoridad del Hijo",
"John.5.31": "Testimonios sobre Jesús",
"John.6.1": "Jesús alimenta a los cinco mil",
"John.6.16": "Jesús camina sobre el agua",
"John.6.22": "La multitud busca a Jesús",
"John.6.25": "Jesús, el pan de vida",
"John.6.26": "Jesucristo, el pan de vida",
"John.6.35": "El que cree tiene vida eterna",
"John.6.48": "El que come de este pan vivirá eternamente",
"John.6.60": "Muchos discípulos abandonan a Jesús",
"John.6.67": "La confesión de Pedro",
"John.7.1": "Jesús va a la Fiesta de los Tabernáculos",
"John.7.10": "Jesús en la Fiesta de los Tabernáculos en Jerusalén",
"John.7.14": "Jesús enseña en la Fiesta",
"John.7.25": "División sobre quién es Jesús",
"John.7.37": "Agua Viva",
"John.7.40": "¿Es Jesús el Mesías?",
"John.7.45": "Incredulidad de los líderes judíos",
"John.8.1": "Una mujer sorprendida en adulterio, Jesús no la condena",
"John.8.12": "Disputa sobre el testimonio de Jesús",
"John.8.21": "Disputa sobre quién es Jesús",
"John.8.31": "Disputa sobre de quiénes son hijos los oponentes de Jesús",
"John.8.37": "¿Hijos de Abraham o del diablo?",
"John.8.48": "Afirmaciones de Jesús sobre mismo",
"John.9.1": "Jesús sana a un hombre ciego de nacimiento",
"John.9.13": "Los fariseos investigan la curación",
"John.9.24": "Rechazo del hombre curado",
"John.9.35": "Ceguera espiritual",
"John.10.1": "El buen pastor y sus ovejas",
"John.10.7": "Jesucristo - la puerta de las ovejas",
"John.10.11": "Jesucristo - el buen pastor",
"John.10.22": "Otro conflicto sobre las afirmaciones de Jesús",
"John.10.31": "Acusación de blasfemia",
"John.11.1": "La muerte de Lázaro",
"John.11.17": "Jesús consuela a las hermanas de Lázaro",
"John.11.28": "Jesús llora",
"John.11.38": "Jesús resucita Lázaro resucita",
"John.11.45": "El complot para matar a Jesús",
"John.12.1": "Jesús ungido en Betania",
"John.12.12": "Jesús llega a Jerusalén como rey",
"John.12.20": "Jesús predice su muerte",
"John.12.27": "Jesús anuncia su muerte",
"John.12.37": "Creencia e incredulidad entre los judíos",
"John.12.42": "Consecuencias de la fe y la incredulidad",
"John.13.1": "Jesús lava los pies de sus discípulos",
"John.13.18": "Jesús predice su traición",
"John.13.12": "Lavado de pies",
"John.13.21": "Anuncio de traición",
"John.13.31": "Jesús predice la muerte de Pedro, negación",
"John.13.33": "El nuevo mandamiento",
"John.13.36": "Jesús anuncia que Pedro lo negará",
"John.14.1": "Jesús consuela a sus discípulos",
"John.14.5": "Jesús el camino hacia el Padre",
"John.14.8": "Quien ve al Hijo ve al Padre",
"John.14.15": "Jesús promete el Espíritu Santo",
"John.14.25": 'Jesús dice: "¡Levantaos, vámonos de aquí!"',
"John.15.1": "La vid y los sarmientos",
"John.15.9": "Permaneced en el amor de Jesús",
"John.15.18": "El mundo odia a los discípulos",
"John.15.26": "La obra del Espíritu Santo",
"John.16.4": "La obra del Espíritu Santo",
"John.16.5": "La obra del Espíritu Santo",
"John.16.16": "El dolor de los discípulos se convertirá en alegría",
"John.16.25": "La victoria de Jesús sobre el mundo",
"John.17.1": "Jesús ora para ser glorificado",
"John.17.6": "Jesús ora por sus discípulos",
"John.17.20": "Jesús ora por todos los creyentes",
"John.18.1": "Jesús arrestado",
"John.18.12": "Jesús ante Anás",
"John.18.15": "La primera negación de Pedro",
"John.18.19": "El sumo sacerdote interroga a Jesús",
"John.18.25": "La segunda y tercera negación de Pedro",
"John.18.28": "Jesús ante Pilato",
"John.18.38": "La condena de Jesús",
"John.19.1": "Jesús condenado a ser crucificado",
"John.19.6": "Jesús no responde a Pilato",
"John.19.16": "La crucifixión de Jesús",
"John.19.17": "La crucifixión de Jesús",
"John.19.28": "La muerte de Jesús",
"John.19.31": "El que ella traspasó tiene«",
"John.19.38": "El entierro de Jesús",
"John.20.1": "El sepulcro vacío",
"John.20.10": "Jesús se aparece a María Magdalena",
"John.20.11": "Jesús se aparece a María Magdalena",
"John.20.19": "Jesús se aparece a sus discípulos",
"John.20.24": "Jesús se aparece a Tomás",
"John.20.30": "El propósito del evangelio de Juan",
"John.21.1": "Jesús y la pesca milagrosa de pescado",
"John.21.15": "Jesús restituye a Pedro",
"John.21.20": "Pedro y el discípulo a quien Jesús amaba especialmente",
"John.21.24": "Palabras finales",
"John.1.1.descr": `Juan presenta a Jesús en estos primeros versículos como el que es plenamente humano y plenamente Dios (ver también Col 2:9).
Aunque él -el Verbo- se hizo carne y habitó entre nosotros (1:14) y se hizo plenamente humano, nunca dejó de ser el Dios eterno y fuente de vida. Juan escribió este Evangelio con la intención de alentar la fe en este Jesús y la confianza en él.
¿En qué preguntas y áreas de la vida quieres fortalecer tu fe en Jesús en los próximos tres meses?`,
"John.1.19.descr": `Juan el Bautista se describe a sí mismo como una voz que llama en el desierto: "Preparad el camino para la venida del Señor" (1:23).
¿Qué caminos en tu vida aún necesitan ser pavimentados para que Jesús tenga libre acceso?
¿Y dónde puedes ser tú quien abra un camino a Jesús para las personas que te rodean?`,
"John.1.29.descr": `Juan el Bautista describe a Jesús como el Cordero de Dios que quita el pecado del mundo (1:29).
¿Cómo ha quitado Jesús los pecados de tu vida y cómo te afecta este hecho en tu vida diaria?`,
"John.1.35.descr": `Andrés lleva a su hermano Simón a Jesús para mostrarle al Salvador. Y en los siguientes versículos, Felipe le hablará a Natanael sobre Jesús y le pedirá que lo vea por sí mismo (1:46).
¿Hay alguien en tu vida que puedas llevar a Jesús?
¿Quizás alguien a quien puedas invitar para que venga y lo vea por sí mismo?`,
"John.1.43.descr": `Lo que sea que haya sucedido allí debajo de la higuera, Natanael sabe que Jesús lo "vio".
¿Has experimentado que Jesús te vea y te conozca de una manera similar?
¿Qué impacto tuvo esto en tu fe?`,
"John.2.1.descr": `El primer milagro de Jesús: el agua se convierte en vino en las bodas de Caná.
¿Cómo experimentas el poder transformador de Jesús en tu propia vida?
¿Dónde quieres esa transformación?`,
"John.2.13.descr": `Jesús purifica el templo y expulsa a los mercaderes (2:15).
¿Qué necesita ser purificado en tu vida para que pueda ser una "casa de oración" y nuestro cuerpo un "templo del Espíritu Santo" (1 Cor. 6:19)?
¿Cómo puedes asegurarte de darle a Jesús el lugar que se merece en tu vida?`,
"John.3.1.descr": `La frase "nacer del agua" se entiende generalmente como una referencia a una conversión personal a Dios (arrepentimiento) y al bautismo cristiano.
¿Qué quiso decir Jesús con la frase de que debemos "nacer del Espíritu"?
¿Has experimentado esto personalmente?`,
"John.3.22.descr": `«Es necesario que Él crezca, pero que yo disminuya» (3:30):
¿Puedes decir esto también de tu vida? ¿Y qué significa en términos prácticos que Jesús tenga cada vez más influencia en tu vida?`,
"John.4.1.descr": `¿Experimentas cómo Jesús calma tu sed una y otra vez y tienes suficiente para dar a otros a beber el «agua de vida»?`,
"John.4.27.descr": `La mujer de Samaria deja su cántaro y cuenta a todos su encuentro con Jesús (4:28).
¿Cuándo fue la última vez que dejaste todo atrás para contar a los demás lo que experimentaste con ÉL?`,
"John.4.43.descr": `Jesús dice un tanto reprochándole que nosotros los humanos a menudo solo podemos creer cuando experimentamos milagros y señales (4:48).
¿Tu fe depende de los milagros?`,
"John.5.1.descr": `Entre todos los enfermos, ciegos y cojos, Jesús cura sólo a un enfermo de larga duración ese día (5:3-5).
¿Cómo explicas la manera en que Jesús trata esto?
¿No le interesa a Jesús ayudar a todos los demás enfermos?`,
"John.5.19.descr": `Jesús se ve a sí mismo como alguien que depende completamente de su Padre celestial: sólo puede hacer lo que ve hacer a su Padre (5:19).
Si Jesús se sometió tan completamente a la voluntad de Dios, ¿qué significado tiene esto para nuestra vida cotidiana y nuestras oraciones?`,
"John.5.31.descr": `Jesús provoca con la afirmación de que la vida eterna no se encuentra en las Escrituras, sino en él (5:39-40).
¿Dónde buscas "vida eterna"?`,
"John.6.1.descr": `Jesús no quiere ser coronado rey por la gente (6:15).
¿Por qué Jesús se aleja de la gente a pesar de ser el "Rey de reyes"?`,
"John.6.16.descr": `Las tormentas parecen ser parte de la vida.
¿En qué situaciones de tormenta necesitas el aliento de Jesús: "No tengas miedo, soy yo!"?`,
"John.6.22.descr": `A veces, Jesús parece haberse ido de repente.
¿Eres de los que pueden dejar los lugares familiares y buscar a Jesús al otro lado (6:25)?`,
"John.6.26.descr": `¿Por qué buscas a Jesús; ¿Porque quieres saciar tu hambre o porque te interesa el mismo Jesús (6,27)?`,
"John.6.35.descr": `Los humanos buscamos la vida en los lugares más diversos y a menudo más imposibles:
¿Te basta tener el pan de vida en Jesús (6,41)?`,
"John.6.48.descr": `Jesús provoca a los judíos de aquel tiempo pidiéndoles que coman su carne y beban su sangre.
¿Puede haber aquí algo más que una simple referencia a la Cena del Señor? En este caso, ¿qué?`,
"John.6.60.descr": `¿Qué impide a la gente de hoy seguir a Jesús?
Compárese con el versículo 66. "Es el Espíritu el que da vida".
Este versículo es como la gasolina en el tanque de la vida de un cristiano.
¿Qué te ayuda a llenar continuamente tu vida espiritual con las palabras de Dios?`,
"John.6.67.descr": `¿Qué le responderías a Jesús si te hiciera esta pregunta?
Comparar versículo 67.
¡Toma nota de todo lo que te ha sido dado en/con Jesús!`,
"John.7.1.descr": `¿Por qué razones la gente todavía odia a Jesús hoy?
Comparar versículo 7. Los hermanos obviamente quieren que Jesús sea celebrado y reconocido por quién es.
¿En qué punto nos encontramos como cristianos y como iglesia en una tentación similar?`,
"John.7.10.descr": `Jesús permanece independiente de la gente y siempre espera las instrucciones del Padre. Al hacerlo, elige el camino de la cruz, para nuestro beneficio.
¿Qué provoca este hecho en ti?
La obediencia práctica, como se describe en el versículo 17, permite que la inspiración divina de la Palabra de Dios se experimente como una realidad en nuestras vidas.
¿Qué experiencias has tenido al respecto?`,
"John.7.25.descr": `La disputa sobre el Mesías "real" está llegando a un punto crítico: los oponentes no pueden hacer frente a Jesús y sus palabras provocadoras y, sin embargo, misteriosas.
¿Usaremos el tiempo que nos queda para vivir de manera adecuada?`,
"John.7.37.descr": `¿Qué paralelismos hay entre los versículos 17 y 38?
¿Por qué es tan importante este énfasis en Jesús? Quien bebe de esta fuente, es decir, confía u obedece a Jesús, se convierte en fuente para los demás.
¿Has recibido el Espíritu Santo?
Si no, ¿qué puedes hacer hoy para recibirlo?`,
"John.7.40.descr": `La feroz disputa sobre Jesús se enciende de nuevo. Incluso el escuadrón de arrestos confirma la singularidad de Jesús.
¿A veces pierdes el coraje de estar al lado de Jesús?
Nicodemo puede ayudarnos; él defiende a Jesús con valentía y sabiduría.`,
"John.8.1.descr": `"Yo tampoco te condeno; puedes irte. ¡No peques más de ahora en adelante!" Jesús le dijo a la mujer.
¿Cómo tratas con las personas que están atrapadas en el pecado?`,
"John.8.12.descr": `Jesús explica que Él es la luz del mundo y que quienes lo siguen no caminarán en tinieblas.
¿En qué áreas de tu vida necesitas la luz de Jesús para encontrar claridad y guía?`,
"John.8.21.descr": `Jesús habla de su muerte inminente y su regreso al Padre, y muchos no lo entienden.
¿Cómo tratas con las cosas que no entiendes completamente en tu fe?`,
"John.8.31.descr": `Jesús dice que la verdad nos hará libres si permanecemos en Su Palabra.
¿Qué verdades de la Palabra de Dios ya te han liberado en tu vida?`,
"John.8.37.descr": `Jesús explica que quienes son de Dios escuchan las palabras de Dios.
¿Cómo escuchas la voz de Dios en tu vida?`,
"John.8.48.descr": `La gente acusa a Jesús de estar poseído por un demonio, pero él responde que honra a Dios.
¿Cómo afrontas las acusaciones o los malentendidos sobre tu fe?`,
"John.9.1.descr": `Jesús sana a un hombre ciego de nacimiento, revelando así las obras de Dios.
¿En qué áreas de tu vida has experimentado la obra y sanación de Dios?`,
"John.9.13.descr": `En aquel entonces, no se permitía que ocurrieran milagros en sábado. Hoy, los milagros contradicen nuestra razón humana.
¿Cómo te sientes ante las acciones milagrosas de Dios aquí y ahora?`,
"John.9.24.descr": `Nuestra historia personal de cómo Jesús cambió nuestras vidas es poderosa:
¿Puedes contar la historia, como el hombre ciego que fue sanado, sobre lo que Jesús hizo en tu vida?`,
"John.9.35.descr": `En realidad, solo el hombre ciego "vio"; aquellos que parecían poder ver eran los que eran ciegos.
¿A qué grupo perteneces?`,
"John.10.1.descr": `Jesús dice que las ovejas conocen la voz de su pastor.
¿Cómo suena la voz de Jesús y cómo reconoces a tu pastor?`,
"John.10.7.descr": `Jesús vino a traer vida, vida en abundancia.
¿Dónde has experimentado que te guiaba hacia la vida más plena?`,
"John.10.11.descr": `La misión de Jesús fue dar su vida en sacrificio.
¿Cuál es la misión que te ha encomendado el Padre celestial?`,
"John.10.22.descr": `Jesús dice que sus acciones hablan por sí solas y prueban que es hijo de su Padre celestial.
¿Qué dicen tus acciones sobre ti?`,
"John.10.31.descr": `La gente reconoce que "todo lo que él (Juan el Bautista) dijo sobre este hombre" ha demostrado ser cierto. Jesús ha demostrado ser verdadero, por eso muchos creyeron en él.
¿Por qué crees en Jesús?`,
"John.11.descr": `Las declaraciones de Jesús no siempre son claras y fáciles de entender. Pero cuando los discípulos le preguntan, les da una respuesta clara.
¿Qué quieres preguntarle a Jesús que todavía no entiendes?`,
"John.11.17.descr": `Jesús dice: "Yo soy la resurrección y la vida".
¿En quién o en qué estás buscando un futuro exitoso y una vida plena?`,
"John.11.28.descr": `"Los ojos de Jesús se llenaron de lágrimas". Jesús sintió emociones humanas como la ira, el dolor y la compasión.
¿Qué circunstancias injustas llenan tus ojos de lágrimas? ¿Por quién sientes compasión?`,
"John.11.38.descr": `"... (inserta tu nombre), ¡sal!" Jesús también te está llamando a ti a volver a la vida.
¿En qué área muerta de tu vida escuchas que Jesús te llama?
Da un paso hacia él, la verdadera vida, y vuelve a la vida.`,
"John.11.45.descr": `"Uno para todos y todos para uno". Con su muerte sacrificial, Jesús ganó la libertad para todos nosotros. Uno murió por todos.
¿Estás listo para vivir completamente para Jesús ahora?`,
"John.12.1.descr": `"Siempre habrá gente pobre a la que puedas atender."
¿A quién cuidas que es pobre?
¿A quién puedes ayudar específicamente en su necesidad hoy o en la próxima semana?`,
"John.12.12.descr": `La palabra "Hosanna" expresa el anhelo de salvación de las personas. Pero Jesús no está buscando "seguidores" (cf. unos días después: Juan 19:15) sino "discípulos".
¿Cuál es la diferencia?`,
"John.12.20.descr": `Con "morir" en realidad significa dejar de lado mi propia voluntad para que de ella puedan venir buenos frutos.
¿Qué podría significar esto específicamente en tu propia vida?
¿Cuál es la consecuencia duradera de esto?`,
"John.12.27.descr": `El "alcanza alto" es una meta soñada para muchos. Para Jesús, su meta era ir “hacia arriba”, hasta llegar a la cruz.
«Caminad mientras tenéis la luz, para que no os sorprendan las tinieblas». ¿Qué puede significar esto para ti?
¿Cómo puedes aprovechar mejor el tiempo que te ha sido dado?`,
"John.12.37.descr": `Muchas personas a nuestro alrededor rechazan a Jesús, eso nos duele, pero Jesús mismo experimentó este rechazo. El amor de Dios brilla con más fuerza y ​​no pierde nada de su resplandor por ello. ¡Eso también debería animarnos!
¿Cómo afrontas el rechazo?
¿Es hora de ser un poco más valientes?`,
"John.12.42.descr": `Jesús resume nuevamente su llamado: Todo lo que Él dice y hace viene del Padre. Esto hace que nuestra responsabilidad de cómo afrontamos lo que Sus palabras nos dicen sea aún mayor.
¿Qué dice el texto sobre las consecuencias positivas y negativas de esta nuestra responsabilidad?`,
"John.13.1.descr": `Aparentemente ninguno de los discípulos estaba preparado para este acto de amor "humillante" al comienzo de la celebración. Jesús muestra que este lavatorio de pies también tiene un personaje simbólico. Es una imagen de nuestra limpieza necesaria y holística a través de la crucifixión de Jesús. (Lea el capítulo 5 de la carta a los Efesios) También puede leer cómo puede ser un "lavatorio de pies" diario y qué implica en 1 Juan 1:7.
¿Los pies de quién puede "lavar" hoy?
¿Y a quién puede pedirle que "lave" sus pies?`,
"John.13.12.descr": `El significado simbólico del lavatorio de pies: Podemos emular el ejemplo de Jesús entre nosotros (en la iglesia). Porque Jesús extiende la misión del Padre a sus seguidores en el versículo 20.
¿Cómo influye esto en su comportamiento?`,
"John.13.21.descr": `La historia de la traición de Judas es bien conocida. Judas es uno de los 12 discípulos - es llamado por Jesús y se queda con él día y noche durante tres años. Sin embargo, traiciona a Jesús.
¿Le ha sucedido esto alguna vez?
¿Cómo lidia con una traición así?`,
"John.13.31.descr": `Jesús nos da un mandamiento nuevo: que nos amemos unos a otros, tal como nos lo mostró en su trato con sus discípulos.
¿Somos reconocidos como comunidad desde fuera por cómo nos amamos unos a otros?
¿Te reconocen personalmente como cristiano por tu amor al prójimo?`,
"John.13.36.descr": `Aquí encontrarás el segundo anuncio de la traición de Jesús. Pedro dice con plena convicción: "¡Daré mi vida por ti!"
¿Te suena familiar este error de juicio en tu vida?
¿Has vivido alguna vez una situación así?`,
"John.14.1.descr": `Los humanos pensamos de manera muy diferente, estamos formados personalmente y percibimos las cosas de manera diferente.
¿Podría ser esta la razón por la que hay diferentes hogares disponibles para nosotros en el cielo?
¿O probablemente viviremos allí como familias extendidas? ¿Qué piensas del cielo?`,
"John.14.8.descr": `Jesús promete aquí algo maravilloso: quien crea en Él puede hacer las mismas obras que Jesús, ¡incluso mayores!
¿Ves esta afirmación relacionada con los milagros o con Su naturaleza, Su actitud y Sus modales?`,
"John.14.15.descr": `Jesús expresa aquí una conexión muy desafiante entre el amor por Él y la obediencia: ¡Si lo amamos, cumplimos sus mandamientos!
¿Cómo te va con el cumplimiento de sus mandamientos en tu vida diaria?
¿Dudas de tu amor por Él o de Su amor por ti?`,
"John.14.25.descr": `Al final de la Última Cena con los muchos temas diferentes que Jesús discutió con los discípulos, dice de manera bastante abrupta:
Levántate y vámonos de aquí.
¿Qué significa eso en el contexto de la Última Cena de aquel entonces y qué significa para ti hoy?`,
"John.15.1.descr": `Jesús dice que Él es la vid verdadera y nosotros los sarmientos (15:1-2). Si permanecemos en Él, daremos mucho fruto.
¿Cuándo fue la última vez que experimentaste conscientemente que permanecías en Jesús y que de ello provenía fruto?
¿Qué significa para ti ser "podado" por Jesús para que puedas dar más fruto (15:2)?`,
"John.15.9.descr": `Jesús nos llama a permanecer en su amor y a guardar sus mandamientos para poder experimentar la alegría (15:9-11).
¿Cómo experimentas la alegría que viene de obedecer sus mandamientos?
¿Qué significa para ti en términos prácticos amarnos unos a otros como Jesús nos amó (15:12)?`,
"John.15.18.descr": `Jesús advierte a sus discípulos que el mundo los odiará porque no son del mundo, así como Él no es del mundo (15:18-19).
¿Alguna vez has experimentado hostilidad o rechazo por creer en Jesús? 16:1-4 ¿Cómo lidias con esto y cómo te ayuda saber que Jesús ya lo ha predicho?`,
"John.16.5.descr": `Jesús promete el Espíritu Santo a sus discípulos, quien los guiará a toda la verdad (16:13).
¿En qué situaciones has sentido la guía del Espíritu Santo de manera particularmente clara en tu vida?
¿Cómo puedes confiar más en el Espíritu Santo y aprender de él en la vida diaria?`,
"John.16.16.descr": `Jesús habla de su inminente partida y del reencuentro, que traerá gran alegría a los discípulos (16:22).
¿Cómo enfrentas los momentos de dolor y pérdida, y dónde encuentras consuelo en la promesa de que Jesús nos volverá a ver?
¿Qué significa para ti pedir en el nombre de Jesús y experimentar la plenitud del gozo (16:24)?`,
"John.16.25.descr": `Jesús promete paz a sus discípulos, incluso cuando experimentarán angustia en el mundo (16:33).
¿En qué momentos de tu vida has experimentado la paz de Jesús a pesar de las circunstancias difíciles?
¿Cómo la confianza en que Jesús ha vencido al mundo te fortalece para enfrentar los desafíos y las crisis?`,
"John.17.1.descr": `Jesús ora a su Padre y pide la glorificación que le corresponde (17:1). Reflexiona sobre la vida eterna y la culminación de su obra en la tierra (17,4).
¿Cómo puedes glorificar a Dios en tu vida y completar la obra que te ha encomendado?
¿Qué significa para ti la vida eterna, que Jesús describe como el reconocimiento del único Dios verdadero y de Jesucristo (17,3)?`,
"John.17.6.descr": `Jesús ora por la unidad entre los creyentes.
¿Es importante también para ti la unidad de los cristianos y cómo puedes aportar algo concreto a esta unidad hoy?`,
"John.17.20.descr": `La gente debe reconocer a partir de la unidad de los creyentes que Jesús es el enviado de Dios (17,21.23).
¿Qué significa para ti que la impotencia del testimonio cristiano esté relacionada con la falta de unidad y amor entre los cristianos?`,
"John.18.1.descr": `Jesús toma la copa del sufrimiento de la mano de su Padre.
¿Qué sufrimientos también debes aceptar de la mano de Dios y cuáles puedes evitar?`,
"John.18.12.descr": `¿Cómo describirías el comportamiento de Jesús en la conversación con el sumo sacerdote Anás y qué podría significar esto para ti en situaciones difíciles?`,
"John.18.15.descr": `¿Conoces momentos en tu vida personal en los que te sientas junto al fuego y niegas a Jesús?`,
"John.18.28.descr": `Jesús nació y vino al mundo para dar testimonio de la verdad. ¿Qué quiere decir Jesús aquí con «verdad»?`,
"John.18.38.descr": `Jesús es entregado a muerte, y el ladrón Barrabás es liberado:
¿Cómo se explica esta «injusticia clamorosa» en aquel momento?`,
"John.19.1.descr": `Pilato espera satisfacer al pueblo enfadado haciendo que azoten y se burlen de Jesús. Se deja guiar por el miedo a la gente.
¿Conocéis también este miedo a la gente, a sus reacciones y declaraciones?
La Biblia dice que la sabiduría comienza con el temor a Dios. ¿Cómo se puede obedecer a Dios más que a la gente y a sus expectativas en el futuro?
Un comentario:
Los soldados tejieron una corona de espinas: Los reyes llevan coronas, pero no coronas de tortura. Esta corona cortó, atravesó y ensangrentó la cabeza del rey que la llevaba. Jesús soportó este tormento y dolor por vosotros.
Luego le pusieron un manto púrpura: Los reyes y gobernantes a menudo vestían de púrpura porque los tintes para producir este color eran caros. El manto púrpura fue pensado como una cruel ironía. Así también Jesús soportó toda la burla y el desprecio en tu lugar. ¿Aceptas su oferta de encontrar la salvación en sus heridas? Compara 1 Pedro 2:24.`,
"John.19.6.descr": `Jesús elige sus palabras con cuidado y pronuncia pocas palabras. Estas palabras son aún más impresionantes cuando analizamos de cerca las reacciones de Pilato.
¿Cómo manejas tus palabras? ¿Pronuncias muchas palabras sobre nada o eliges palabras apropiadas y verdaderas?
¿Eres capaz de hablar cuando se trata de tu identidad en Cristo?`,
"John.19.17.descr": `"Jesús de Nazaret, el Rey de los judíos". La identidad de Jesús y su papel en la historia humana fue controvertida desde el principio. Algunos de los gobernantes judíos no lo querían como rey y rechazaron sus orígenes. Sin embargo, Jesús sigue siendo quien es.
¿Es Jesús también tu rey?
¿Cómo te comportas con tu Rey? ¿Necesitas cambiar tu actitud y tu trato con él?`,
"John.19.28.descr": `"¡Está consumado!" Él lo ha hecho por ti. La salvación se debe únicamente a las acciones de Dios.
¿Crees eso?
¿Quieres aceptar hoy de nuevo o una vez más el don de la gracia y del perdón?`,
"John.19.31.descr": `Jesucristo es "aquel a quien traspasaron". Fue traspasado en nuestro lugar. Tomó tu lugar y murió por ti.
¿Cómo puedes agradecerle a Dios por eso hoy?
¿Cómo vives una vida de agradecimiento y en una nueva y regalada libertad de la culpa?`,
"John.19.38.descr": `Jesús fue enterrado en una tumba nueva. Fue confirmado muerto y su cuerpo estaba sin vida.
¿Tienes cosas en tu vida que huelen a muerte, destrucción o sufrimiento?
¿Tuviste que enterrar a seres queridos, sueños o esperanzas?
Lleva tu dolor a Jesús en oración y llora con él por tu pérdida.`,
"John.20.1.descr": `"¡Jesús ha resucitado!" - Cuando el discípulo, aquel a quien Jesús amaba, fue al sepulcro y vio todo, creyó. ¿Qué tienes que ver para poder creer?
¿Qué da seguridad a tu fe?
Los primeros cristianos y apóstoles estaban tan llenos de fe y convicción que todos estaban dispuestos a morir por esta verdad.`,
"John.20.10.descr": `María Magdalena se encuentra con Jesús resucitado y no lo reconoce al principio (20:14). No podía verlo porque no esperaba verlo. Entonces la llamó por su nombre y ella lo reconoció de inmediato (20:16).
¿Cómo reaccionarías si Jesús se encontrara contigo personalmente? ¿Lo escuchas llamándote inequívocamente por tu nombre?`,
"John.20.19.descr": `Jesús se aparece a los discípulos en su desilusión y temor y les dice: “¡La paz esté con ustedes!” (20:19).
¿Cómo experimentas la paz de Jesús en tu vida?
¿Dónde deseas que Jesús venga y traiga paz y alegría?`,
"John.20.24.descr": `Tomás duda de la resurrección y quiere ver a Jesús para creer (20:25). Jesús no critica esta duda sincera.
Jesús sale al encuentro de Tomás en el sentido que necesita. ¿Tienes tú también dudas?
Entonces no te detengas en este punto, sino ve en busca de respuestas. Jesús te saldrá al encuentro y tus dudas pueden llevar a una profundización de tu fe.`,
"John.20.30.descr": `Juan resume nuevamente su intención:
Escribió la obra de Jesús para que podamos creer y tener vida por la fe (20:31).
¿Cómo ha fortalecido tu fe la lectura y la observación del Evangelio de Juan en las últimas semanas?
Cuéntale a alguien tu experiencia y tus vivencias.`,
"John.21.1.descr": `Qué escena más hermosa:
Después de todo el ajetreo de los últimos días, Jesús prepara el desayuno para sus discípulos y los invita a sentarse a comer con él.
¿Dónde te invita hoy Jesús a simplemente “sentarte” con él, a tener comunión con él y a dejarte cuidar?`,
"John.21.15.descr": `Después de que Jesús fortaleció físicamente a los discípulos con el desayuno y creó un espacio seguro, fortaleció personalmente a Pedro después de su negación (Juan 18). Jesús le pregunta a Pedro tres veces si lo ama y le da la tarea de cuidar sus ovejas (21:17).
¿Cómo respondes a la pregunta de Jesús: “¿Me amas?”
¿Qué tareas has asumido a través de tu amor por Jesús?`,
"John.21.20.descr": `Pedro pregunta sobre el destino del discípulo a quien Jesús amaba (21:21). También nosotros corremos el peligro de compararnos con otros en nuestra vida de fe.
¿Qué significa para ti la llamada de Jesús: “Sígueme” (21:22)?`
}
